version: 2
gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
builds:
  -
    id: "edi-connector"
    binary: edi-connector
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/myopenfactory/edi-connector/version.Version={{.Version}} -X github.com/myopenfactory/edi-connector/version.Date={{.Date}} -X github.com/myopenfactory/edi-connector/version.Commit={{.Commit}}
archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
      - README.md
      - THIRD_PARTY/*
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
release:
  prerelease: auto
