before:
  hooks:
    - go mod download
builds:
  -
    binary: myof-client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
    ldflags:
      - -X github.com/myopenfactory/client/pkg/version.Version={{.Version}} -X github.com/myopenfactory/client/pkg/version.Date={{.Date}} -X github.com/myopenfactory/client/pkg/version.Commit={{.Commit}}
archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - THIRD_PARTY/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - myof-client
    dockerfile: Dockerfile
    image_templates:
      - "myopenfactory/client:alpine"
      - "myopenfactory/client:latest"
    extra_files:
      - myOpenFactoryCA.crt
signs:
  - signature: "${artifact}.sig"
    cmd: openssl
    args: ["dgst", "-sha256", "-sign", "$HOME/key.asc", "-out", "${signature}", "${artifact}"]
    artifacts: all
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
