url: http://localhost:8081
username: endpoint@a.com
password: test
log:
  # folder: "/home/tobiaskohlbau/tmp/edi-connector/logs"
# log:
#   mail:
#     host: localhost
#     port: 1025
#     from: "ediconnector@ediplatform.services"
#     to: "tobias@kohlbau.com"
outbounds:
  - id: kjLh3y
    type: FILE
    settings:
      messages:
        - path: /home/tobiaskohlbau/tmp/edi-connector/outbound
          extensions:
            - edi
            - xml
      attachments:
        - path: /home/tobiaskohlbau/tmp/edi-connector/outbound_attachments
          extensions:
            - edi
            - xml
      errorPath: /home/tobiaskohlbau/tmp/edi-connector/error
      successPath: /home/tobiaskohlbau/tmp/edi-connector/success
inbounds:
  - id: B20pW6
    type: FILE
    settings:
      path: /home/tobiaskohlbau/tmp/edi-connector/inbound
      attachmentPath: /home/tobiaskohlbau/tmp/edi-connector/inbound_attachments
      attachmentWhitelist:
        - ediplatform.com
