# escape=`

FROM microsoft/windowsservercore:latest
COPY . C:\
SHELL ["powershell", "-command"]
RUN Import-Certificate -FilePath C:\myOpenFactoryCA.crt -CertStoreLocation cert:\LocalMachine\Root
CMD ["C:\myof-client.exe"]