// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Log_Level int32

const (
	Log_DEBUG Log_Level = 0
	Log_INFO  Log_Level = 1
	Log_WARN  Log_Level = 2
	Log_ERROR Log_Level = 3
)

var Log_Level_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "WARN",
	3: "ERROR",
}
var Log_Level_value = map[string]int32{
	"DEBUG": 0,
	"INFO":  1,
	"WARN":  2,
	"ERROR": 3,
}

func (x Log_Level) String() string {
	return proto.EnumName(Log_Level_name, int32(x))
}
func (Log_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{3, 0}
}

// List of Messages
type Messages struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{0}
}
func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (dst *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(dst, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

// Message is a edi message with extra information
type Message struct {
	ProcessId            string            `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Id                   string            `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Test                 bool              `protobuf:"varint,3,opt,name=test,proto3" json:"test,omitempty"`
	Properties           map[string]string `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Content              []byte            `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Attachments          []*Attachment     `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetTest() bool {
	if m != nil {
		return m.Test
	}
	return false
}

func (m *Message) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetAttachments() []*Attachment {
	if m != nil {
		return m.Attachments
	}
	return nil
}

// Confirmation of a message
type Confirm struct {
	ProcessId            string   `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	StatusCode           int32    `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Confirm) Reset()         { *m = Confirm{} }
func (m *Confirm) String() string { return proto.CompactTextString(m) }
func (*Confirm) ProtoMessage()    {}
func (*Confirm) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{2}
}
func (m *Confirm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confirm.Unmarshal(m, b)
}
func (m *Confirm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confirm.Marshal(b, m, deterministic)
}
func (dst *Confirm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confirm.Merge(dst, src)
}
func (m *Confirm) XXX_Size() int {
	return xxx_messageInfo_Confirm.Size(m)
}
func (m *Confirm) XXX_DiscardUnknown() {
	xxx_messageInfo_Confirm.DiscardUnknown(m)
}

var xxx_messageInfo_Confirm proto.InternalMessageInfo

func (m *Confirm) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

func (m *Confirm) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Confirm) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Confirm) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *Confirm) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

type Log struct {
	Level                Log_Level `protobuf:"varint,1,opt,name=level,proto3,enum=api.Log_Level" json:"level,omitempty"`
	Description          string    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{3}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (dst *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(dst, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetLevel() Log_Level {
	if m != nil {
		return m.Level
	}
	return Log_DEBUG
}

func (m *Log) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Configuration struct {
	Inbound              []*ProcessConfig `protobuf:"bytes,1,rep,name=inbound,proto3" json:"inbound,omitempty"`
	Outbound             []*ProcessConfig `protobuf:"bytes,2,rep,name=outbound,proto3" json:"outbound,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{5}
}
func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (dst *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(dst, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetInbound() []*ProcessConfig {
	if m != nil {
		return m.Inbound
	}
	return nil
}

func (m *Configuration) GetOutbound() []*ProcessConfig {
	if m != nil {
		return m.Outbound
	}
	return nil
}

type ProcessConfig struct {
	ProcessId            string            `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Type                 string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Parameter            map[string]string `protobuf:"bytes,3,rep,name=parameter,proto3" json:"parameter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProcessConfig) Reset()         { *m = ProcessConfig{} }
func (m *ProcessConfig) String() string { return proto.CompactTextString(m) }
func (*ProcessConfig) ProtoMessage()    {}
func (*ProcessConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{6}
}
func (m *ProcessConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessConfig.Unmarshal(m, b)
}
func (m *ProcessConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessConfig.Marshal(b, m, deterministic)
}
func (dst *ProcessConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessConfig.Merge(dst, src)
}
func (m *ProcessConfig) XXX_Size() int {
	return xxx_messageInfo_ProcessConfig.Size(m)
}
func (m *ProcessConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessConfig proto.InternalMessageInfo

func (m *ProcessConfig) GetProcessId() string {
	if m != nil {
		return m.ProcessId
	}
	return ""
}

func (m *ProcessConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProcessConfig) GetParameter() map[string]string {
	if m != nil {
		return m.Parameter
	}
	return nil
}

type Attachment struct {
	Filename    string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Version     string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*Attachment_Data
	//	*Attachment_Url
	Content              isAttachment_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{7}
}
func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attachment.Unmarshal(m, b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
}
func (dst *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(dst, src)
}
func (m *Attachment) XXX_Size() int {
	return xxx_messageInfo_Attachment.Size(m)
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

type isAttachment_Content interface {
	isAttachment_Content()
}

type Attachment_Data struct {
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3,oneof"`
}
type Attachment_Url struct {
	Url string `protobuf:"bytes,6,opt,name=url,proto3,oneof"`
}

func (*Attachment_Data) isAttachment_Content() {}
func (*Attachment_Url) isAttachment_Content()  {}

func (m *Attachment) GetContent() isAttachment_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Attachment) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Attachment) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Attachment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Attachment) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Attachment) GetData() []byte {
	if x, ok := m.GetContent().(*Attachment_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Attachment) GetUrl() string {
	if x, ok := m.GetContent().(*Attachment_Url); ok {
		return x.Url
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Attachment) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Attachment_OneofMarshaler, _Attachment_OneofUnmarshaler, _Attachment_OneofSizer, []interface{}{
		(*Attachment_Data)(nil),
		(*Attachment_Url)(nil),
	}
}

func _Attachment_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Attachment)
	// content
	switch x := m.Content.(type) {
	case *Attachment_Data:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Data)
	case *Attachment_Url:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Url)
	case nil:
	default:
		return fmt.Errorf("Attachment.Content has unexpected type %T", x)
	}
	return nil
}

func _Attachment_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Attachment)
	switch tag {
	case 5: // content.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Content = &Attachment_Data{x}
		return true, err
	case 6: // content.url
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Content = &Attachment_Url{x}
		return true, err
	default:
		return false, nil
	}
}

func _Attachment_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Attachment)
	// content
	switch x := m.Content.(type) {
	case *Attachment_Data:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Data)))
		n += len(x.Data)
	case *Attachment_Url:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Url)))
		n += len(x.Url)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HealthInfo struct {
	Cpu                  float64  `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram                  float64  `protobuf:"fixed64,2,opt,name=ram,proto3" json:"ram,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Threads              uint32   `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"`
	Uptime               uint64   `protobuf:"varint,5,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Os                   string   `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthInfo) Reset()         { *m = HealthInfo{} }
func (m *HealthInfo) String() string { return proto.CompactTextString(m) }
func (*HealthInfo) ProtoMessage()    {}
func (*HealthInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_a9de49dd3adb1c10, []int{8}
}
func (m *HealthInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthInfo.Unmarshal(m, b)
}
func (m *HealthInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthInfo.Marshal(b, m, deterministic)
}
func (dst *HealthInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthInfo.Merge(dst, src)
}
func (m *HealthInfo) XXX_Size() int {
	return xxx_messageInfo_HealthInfo.Size(m)
}
func (m *HealthInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HealthInfo proto.InternalMessageInfo

func (m *HealthInfo) GetCpu() float64 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *HealthInfo) GetRam() float64 {
	if m != nil {
		return m.Ram
	}
	return 0
}

func (m *HealthInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *HealthInfo) GetThreads() uint32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *HealthInfo) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *HealthInfo) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func init() {
	proto.RegisterType((*Messages)(nil), "api.Messages")
	proto.RegisterType((*Message)(nil), "api.Message")
	proto.RegisterMapType((map[string]string)(nil), "api.Message.PropertiesEntry")
	proto.RegisterType((*Confirm)(nil), "api.Confirm")
	proto.RegisterType((*Log)(nil), "api.Log")
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*Configuration)(nil), "api.Configuration")
	proto.RegisterType((*ProcessConfig)(nil), "api.ProcessConfig")
	proto.RegisterMapType((map[string]string)(nil), "api.ProcessConfig.ParameterEntry")
	proto.RegisterType((*Attachment)(nil), "api.Attachment")
	proto.RegisterType((*HealthInfo)(nil), "api.HealthInfo")
	proto.RegisterEnum("api.Log_Level", Log_Level_name, Log_Level_value)
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_a9de49dd3adb1c10) }

var fileDescriptor_api_a9de49dd3adb1c10 = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcf, 0x8b, 0xe4, 0x44,
	0x14, 0x9e, 0x24, 0xdd, 0xd3, 0xdd, 0xaf, 0x7f, 0x6c, 0xf3, 0x58, 0x24, 0x34, 0x2b, 0xf6, 0x06,
	0x0f, 0xad, 0x68, 0x60, 0x67, 0x05, 0x45, 0x56, 0xa4, 0x67, 0x1c, 0x9d, 0x81, 0x71, 0x77, 0x28,
	0x15, 0x8f, 0x43, 0x6d, 0xaa, 0xa6, 0xa7, 0x30, 0x49, 0x85, 0xaa, 0xca, 0x40, 0xdf, 0x3c, 0x7b,
	0xf3, 0x22, 0xf8, 0xbf, 0x78, 0xf1, 0x3f, 0x93, 0xaa, 0x54, 0x7a, 0xd2, 0xbd, 0xc8, 0x32, 0xb7,
	0xf7, 0xe3, 0x7b, 0x55, 0xdf, 0x7b, 0xef, 0x4b, 0x05, 0x46, 0xb4, 0x12, 0x69, 0xa5, 0xa4, 0x91,
	0x18, 0xd1, 0x4a, 0x24, 0x5f, 0xc0, 0xf0, 0x47, 0xae, 0x35, 0xdd, 0x70, 0x8d, 0x2b, 0x18, 0x16,
	0xde, 0x8e, 0x83, 0x65, 0xb4, 0x1a, 0x9f, 0x4c, 0x52, 0x0b, 0xf7, 0x00, 0xb2, 0xcb, 0x26, 0x7f,
	0x85, 0x30, 0xf0, 0x51, 0xfc, 0x10, 0xa0, 0x52, 0x32, 0xe3, 0x5a, 0xdf, 0x08, 0x16, 0x07, 0xcb,
	0x60, 0x35, 0x22, 0x23, 0x1f, 0xb9, 0x64, 0x38, 0x83, 0x50, 0xb0, 0x38, 0x74, 0xe1, 0x50, 0x30,
	0x44, 0xe8, 0x19, 0xae, 0x4d, 0x1c, 0x2d, 0x83, 0xd5, 0x90, 0x38, 0x1b, 0x5f, 0xb9, 0x23, 0x2a,
	0xae, 0x8c, 0xe0, 0x3a, 0xee, 0xb9, 0xab, 0x9f, 0x75, 0xaf, 0x4e, 0xaf, 0x77, 0xe9, 0xf3, 0xd2,
	0xa8, 0x2d, 0xe9, 0xe0, 0x31, 0x86, 0x41, 0x26, 0x4b, 0xc3, 0x4b, 0x13, 0xf7, 0x97, 0xc1, 0x6a,
	0x42, 0x5a, 0x17, 0x5f, 0xc0, 0x98, 0x1a, 0x43, 0xb3, 0xbb, 0x82, 0x97, 0x46, 0xc7, 0xc7, 0xee,
	0xe0, 0x27, 0xee, 0xe0, 0xf5, 0x2e, 0x4e, 0xba, 0x98, 0xc5, 0x37, 0xf0, 0xe4, 0xe0, 0x2e, 0x9c,
	0x43, 0xf4, 0x1b, 0xdf, 0xfa, 0xce, 0xac, 0x89, 0x4f, 0xa1, 0x7f, 0x4f, 0xf3, 0x9a, 0xfb, 0xb6,
	0x1a, 0xe7, 0xeb, 0xf0, 0xab, 0x20, 0xf9, 0x33, 0x80, 0xc1, 0x99, 0x2c, 0x6f, 0x85, 0x2a, 0x1e,
	0x3b, 0x98, 0x18, 0x06, 0xba, 0xce, 0x6c, 0xd2, 0xcf, 0xa6, 0x75, 0xf1, 0x19, 0xf4, 0x72, 0xb9,
	0x69, 0x07, 0x33, 0x74, 0xfc, 0xaf, 0xe4, 0x86, 0xb8, 0x28, 0x7e, 0x04, 0x63, 0x6d, 0xa8, 0xa9,
	0xf5, 0x4d, 0x26, 0x19, 0x77, 0x23, 0xe8, 0x13, 0x68, 0x42, 0x67, 0x92, 0xf1, 0xe4, 0xf7, 0x00,
	0xa2, 0x2b, 0xb9, 0xc1, 0x8f, 0xa1, 0x9f, 0xf3, 0x7b, 0x9e, 0x3b, 0x2a, 0xb3, 0x93, 0x59, 0x7b,
	0x4e, 0x7a, 0x65, 0xa3, 0xa4, 0x49, 0xe2, 0x12, 0xc6, 0x8c, 0xeb, 0x4c, 0x89, 0xca, 0x08, 0x59,
	0x7a, 0x7e, 0xdd, 0x50, 0xf2, 0x02, 0xfa, 0xae, 0x02, 0x47, 0xd0, 0xff, 0xee, 0xfc, 0xf4, 0x97,
	0x1f, 0xe6, 0x47, 0x38, 0x84, 0xde, 0xe5, 0xeb, 0xef, 0xdf, 0xcc, 0x03, 0x6b, 0xfd, 0xba, 0x26,
	0xaf, 0xe7, 0xa1, 0x4d, 0x9f, 0x13, 0xf2, 0x86, 0xcc, 0xa3, 0x64, 0x00, 0xfd, 0xf3, 0xa2, 0x32,
	0xdb, 0xa4, 0x80, 0xa9, 0x1b, 0xcf, 0xa6, 0x56, 0xd4, 0x1e, 0x86, 0x9f, 0xc1, 0x40, 0x94, 0x6f,
	0x65, 0x5d, 0x32, 0x2f, 0x39, 0x74, 0xb4, 0xae, 0x9b, 0x31, 0x35, 0x58, 0xd2, 0x42, 0x30, 0x85,
	0xa1, 0xac, 0x4d, 0x03, 0x0f, 0xff, 0x17, 0xbe, 0xc3, 0x24, 0xff, 0x06, 0x30, 0xdd, 0xcb, 0xbd,
	0x6f, 0x29, 0x56, 0x9d, 0xdb, 0xaa, 0x5d, 0xac, 0xb3, 0xf1, 0x5b, 0x18, 0x55, 0x54, 0xd1, 0x82,
	0x1b, 0xae, 0xe2, 0xc8, 0xdd, 0xfa, 0xfc, 0xdd, 0x5b, 0xd3, 0xeb, 0x16, 0xd3, 0x28, 0xf4, 0xa1,
	0x66, 0xf1, 0x0a, 0x66, 0xfb, 0xc9, 0x47, 0x49, 0xea, 0x9f, 0x00, 0xe0, 0x41, 0xad, 0xb8, 0x80,
	0xe1, 0xad, 0xc8, 0x79, 0x49, 0x0b, 0xee, 0xeb, 0x77, 0x3e, 0x3e, 0x87, 0x89, 0x97, 0xfe, 0x4d,
	0xa7, 0x8b, 0xb1, 0x8f, 0xfd, 0x6c, 0x9b, 0x39, 0x58, 0x6f, 0xf4, 0xce, 0x7a, 0xad, 0x0e, 0xef,
	0xb9, 0xd2, 0x36, 0xdb, 0x73, 0xd9, 0xd6, 0xc5, 0xa7, 0xd0, 0x63, 0xd4, 0xd0, 0xe6, 0x2b, 0xbb,
	0x38, 0x22, 0xce, 0x43, 0x84, 0xa8, 0x56, 0x79, 0x7c, 0x6c, 0xb1, 0x17, 0x47, 0xc4, 0x3a, 0xa7,
	0xa3, 0xdd, 0x27, 0x99, 0xfc, 0x11, 0x00, 0x5c, 0x70, 0x9a, 0x9b, 0xbb, 0xcb, 0xf2, 0x56, 0xda,
	0xce, 0xb3, 0xaa, 0x76, 0xcc, 0x03, 0x62, 0x4d, 0x1b, 0x51, 0xb4, 0x70, 0x5c, 0x03, 0x62, 0x4d,
	0xfc, 0x00, 0x8e, 0x1b, 0xf9, 0x7a, 0x7a, 0xde, 0xb3, 0xcc, 0xcc, 0x9d, 0xe2, 0x94, 0x69, 0xc7,
	0x6c, 0x4a, 0x5a, 0xd7, 0x56, 0xd4, 0x95, 0x11, 0x45, 0x23, 0xff, 0x1e, 0xf1, 0x9e, 0xfd, 0xc6,
	0xa4, 0x6e, 0xa8, 0x91, 0x50, 0xea, 0x93, 0xbf, 0x43, 0x98, 0x9e, 0xe5, 0x82, 0x97, 0xe6, 0x27,
	0xae, 0xee, 0x45, 0xc6, 0xf1, 0x73, 0x18, 0x5f, 0x09, 0x6d, 0x9a, 0x1d, 0x6a, 0x04, 0xb7, 0x58,
	0xa7, 0xd5, 0x45, 0x23, 0xad, 0x7d, 0xb9, 0xa6, 0x30, 0x5d, 0x33, 0xd6, 0x59, 0xc7, 0xe1, 0x6b,
	0xb2, 0x98, 0x3c, 0x54, 0xa9, 0x02, 0x57, 0x00, 0x6b, 0xc6, 0xda, 0xa7, 0x72, 0xef, 0x39, 0x3d,
	0x40, 0x7e, 0x02, 0x13, 0x4b, 0x64, 0xf7, 0x18, 0x77, 0x99, 0x4c, 0xbb, 0x75, 0x1a, 0x3f, 0x85,
	0x99, 0xaf, 0xda, 0x3f, 0xd8, 0x07, 0x17, 0x9d, 0x52, 0x5c, 0xc1, 0x68, 0xcd, 0x58, 0xb3, 0x00,
	0x4f, 0xf6, 0x61, 0x1b, 0x5d, 0xe4, 0xe9, 0x97, 0xf0, 0x32, 0x93, 0x45, 0x5a, 0x6c, 0x65, 0xc5,
	0xcb, 0x5b, 0x9a, 0x19, 0xa9, 0xb6, 0x29, 0xad, 0xaa, 0x5c, 0x64, 0xae, 0xf7, 0xd4, 0x28, 0x5a,
	0xea, 0x4a, 0x2a, 0xa3, 0xd3, 0xcc, 0xcd, 0xd0, 0x16, 0x5f, 0x07, 0x6f, 0x8f, 0xdd, 0xef, 0xe4,
	0xe5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xf0, 0xf0, 0x15, 0x5b, 0x06, 0x00, 0x00,
}
